### ISSUE TITLE
Non-functional

### ISSUE THREAD

**Issue by CallmePyrus** [Save14/RocketLeagueAutoBump#1]
It'd appear that it's no longer functional, is it going to be further working on or is the project ended?

**Comment by Save14** [comment]
Yes, due to updates rocket-league.com, it no longer works. I'm not going to continue development, you can fork it.

**Comment by CallmePyrus** [comment]
Interested in fixing it up in exchange for a payment?

**Comment by Save14** [comment]
@CallmePyrus rocket-league.com added a steam account linking and banlist, so I can't make auto register as it was before. I can make simple autobumper that works with trade offer url. Is this right for you?

**Comment by CallmePyrus** [comment]
@Save14 All I need is the auto-bumper function, already got an account link with steam etc.

I got like 10-12 trades that I wanted bumped every 16 minutes, if you can do that I'll be willing to pay a little. 

Thanks in advance! 

(But yes, if you can make it so I can add several URLs to be bumped, that'll work out)

**Comment by Save14** [comment]
@CallmePyrus pm me on gitter, please
https://gitter.im/Save14
